server:
  port: 8080
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  datasource:
    url: jdbc:mysql://47.52.157.51:3306/design?useAffectedRows=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&useAffectedRows=true
    username: clown
    password: woaini
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
mybatis:
  type-aliases-package: com.clown.design.entity
  mapper-locations: classpath:mapper/*.xml